from __future__ import annotations

from datetime import datetime

from c_score_common import (
    CURRENT_BEST_ONNX_DIR,
    CURRENT_SCOREBOARD,
    KAGGLEGOLF_ROOT,
    SCORE_DOCS,
    ensure_dirs,
    current_scoreboard,
    p0_p1_tasks,
    priority_rank,
    task_index,
    task_manifest,
    write_csv,
    write_md,
)


def main() -> None:
    ensure_dirs()
    manifest = task_manifest()
    scoreboard = current_scoreboard()
    index = task_index()
    rows = []
    for r in manifest:
        task = r["task"]
        score = scoreboard.get(task, {})
        current_cost = float(score.get("total_cost") or r["cost"])
        current_points = float(score.get("current_score") or r["points"])
        gap_to_25 = max(0.0, 25.0 - current_points)
        p_rank = priority_rank(r["priority_band"])
        same_shape_bonus = 1.2 if r["shape_class"] == "same_shape" else 0.8
        palette_bonus = 1.1 if r["color_class"] == "input_palette_only" else 0.9
        quick_win_score = (4 - min(p_rank, 3)) * 10 + gap_to_25 * 2 + (current_cost ** 0.5) * same_shape_bonus * palette_bonus / 12
        rows.append(
            {
                "task": task,
                "priority_band": r["priority_band"],
                "assignment_cost": r["cost"],
                "assignment_points": r["points"],
                "current_cost": round(current_cost, 3),
                "current_points": round(current_points, 6),
                "gap_to_25": round(gap_to_25, 6),
                "shape_class": r["shape_class"],
                "size_trend": r["size_trend"],
                "color_class": r["color_class"],
                "examples": r["examples"],
                "json_bytes": index.get(task, {}).get("bytes", ""),
                "quick_win_score": round(quick_win_score, 6),
                "first_action": "artifact_cost_scan_then_full_validate" if r["priority_band"] in {"P0_lt16", "P1_16_16p7"} else "defer_until_p0p1_done",
            }
        )
    rows = sorted(rows, key=lambda x: (-float(x["quick_win_score"]), x["task"]))
    write_csv(SCORE_DOCS / "10_C_SCORE_PRIORITY_TABLE.csv", rows)

    top = [r for r in rows if r["priority_band"] in {"P0_lt16", "P1_16_16p7"}]
    lines = [
        "# C Score Priority Table",
        "",
        f"Generated: {datetime.now().isoformat(timespec='seconds')}",
        "",
        "Scoring uses current local task scoreboard when available, otherwise assignment cost/points.",
        "",
        "| rank | task | priority | current_cost | current_points | shape | color | quick_win_score | first_action |",
        "| ---: | --- | --- | ---: | ---: | --- | --- | ---: | --- |",
    ]
    for i, r in enumerate(rows, 1):
        lines.append(
            f"| {i} | {r['task']} | {r['priority_band']} | {r['current_cost']} | {r['current_points']} | {r['shape_class']}/{r['size_trend']} | {r['color_class']} | {r['quick_win_score']} | {r['first_action']} |"
        )
    write_md(SCORE_DOCS / "10_C_SCORE_PRIORITY_TABLE.md", "\n".join(lines))

    q = [
        "# C P0/P1 Quick-Win Scan",
        "",
        f"Generated: {datetime.now().isoformat(timespec='seconds')}",
        "",
        f"Current best ONNX dir used as baseline: `{CURRENT_BEST_ONNX_DIR}`",
        f"Current scoreboard: `{CURRENT_SCOREBOARD}`",
        f"External artifact root: `{KAGGLEGOLF_ROOT}`",
        "",
        "## Top P0/P1 Targets",
        "",
        "| rank | task | priority | current_cost | current_points | shape | color | action |",
        "| ---: | --- | --- | ---: | ---: | --- | --- | --- |",
    ]
    for i, r in enumerate(top, 1):
        q.append(
            f"| {i} | {r['task']} | {r['priority_band']} | {r['current_cost']} | {r['current_points']} | {r['shape_class']}/{r['size_trend']} | {r['color_class']} | run `c_score_scan_artifacts.py --tasks {r['task']} --score-top-n 8 --full-validate` |"
        )
    write_md(SCORE_DOCS / "11_C_QUICK_WIN_SCAN.md", "\n".join(q))

    state = [
        "# Current C Score Work State",
        "",
        f"Generated: {datetime.now().isoformat(timespec='seconds')}",
        "",
        "- C group tasks identified: 67 primary tasks.",
        f"- P0/P1 tasks identified: {len(p0_p1_tasks())} (`{', '.join(p0_p1_tasks())}`).",
        "- P0/P1 task cards: generated by `c_task_card_generator.py` in this run.",
        "- ONNX artifacts: local artifact roots exist under `E:/kagglegolf`; C workspace stores indexes, not `.onnx` files.",
        "- Cost command: `python \"workplace C/neurogolf-2026-work/scripts/c_score_scan_artifacts.py\" --tasks P0P1 --score-top-n N --full-validate`.",
        "- Validator command: `python \"workplace C/neurogolf-2026-work/scripts/c_validate_candidate.py\" --candidate-dir <dir>`.",
        "- Public notebook intel: local Kaggle/kagglegolf outputs include prvsiyan 7266.72 and task-level ONNX public sources.",
        "- Candidate submission: none accepted yet in this workspace until a validated cost-lower artifact is found.",
        "- Current route: Mode B + Mode A. Build tools, scan P0/P1 artifacts, accept only full-validation cost reductions.",
    ]
    write_md(SCORE_DOCS / "00_CURRENT_SCORE_WORK_STATE.md", "\n".join(state))
    print(SCORE_DOCS / "11_C_QUICK_WIN_SCAN.md")


if __name__ == "__main__":
    main()
